[theme]
primaryColor="#FF6B00"
backgroundColor="#000000"
secondaryBackgroundColor="#111111"
textColor="#FFFFFF"
font="sans serif"
base="dark"

[ui]
hideSidebarNav=true

[server]
headless=true
enableCORS=false
enableXsrfProtection=false
